/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editordeformulas.vista;

import editordeformulas.controlador.Controlador;
import editordeformulas.modelo.Formula;
import editordeformulas.modelo.Modelo;
import java.io.File;
import java.util.Observable;
import java.util.Observer;
import javafx.beans.InvalidationListener;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author rebeg
 */
public class VentanaPrincipal extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        this.controlador = new Controlador();
        initComponents();
        controlador.registrar(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        archivoMenu = new javax.swing.JMenu();
        abrirArchivoMenuItem = new javax.swing.JMenuItem();
        edicionMenu = new javax.swing.JMenu();
        vistaMenu = new javax.swing.JMenu();
        herramientaMenu = new javax.swing.JMenu();
        ventanaMenu = new javax.swing.JMenu();
        ayudaMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editor de Fórmulas");

        archivoMenu.setText("Archivo");
        archivoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivoMenuActionPerformed(evt);
            }
        });

        abrirArchivoMenuItem.setText("Abrir Archivo");
        abrirArchivoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirArchivoMenuItemActionPerformed(evt);
            }
        });
        archivoMenu.add(abrirArchivoMenuItem);

        jMenuBar1.add(archivoMenu);

        edicionMenu.setText("Edición");
        edicionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edicionMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(edicionMenu);

        vistaMenu.setText("Vista");
        vistaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vistaMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(vistaMenu);

        herramientaMenu.setText("Herramientas");
        herramientaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                herramientaMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(herramientaMenu);

        ventanaMenu.setText("Ventana");
        ventanaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventanaMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(ventanaMenu);

        ayudaMenu.setText("Ayuda");
        ayudaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(ayudaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1083, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void archivoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivoMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_archivoMenuActionPerformed

    private void edicionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edicionMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edicionMenuActionPerformed

    private void vistaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vistaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vistaMenuActionPerformed

    private void herramientaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_herramientaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_herramientaMenuActionPerformed

    private void ventanaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventanaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ventanaMenuActionPerformed

    private void ayudaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ayudaMenuActionPerformed

    private void abrirArchivoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirArchivoMenuItemActionPerformed
        JFileChooser selectorArchivos = new JFileChooser();
        selectorArchivos.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int seleccion = selectorArchivos.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = selectorArchivos.getSelectedFile();
            controlador.leerTxt(archivo);
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún archivo", "ARCHIVO-ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_abrirArchivoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    public void nuevaVentana(Modelo modelo) {
        VentanaFormulaB ventanaFormulaB = new VentanaFormulaB(String.format("Formula %d", this.contador), this.controlador, modelo.getFormula(this.contador));
        contador++;
        ventanaFormulaB.init();
    }

    private Controlador controlador;
    int contador = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirArchivoMenuItem;
    private javax.swing.JMenu archivoMenu;
    private javax.swing.JMenu ayudaMenu;
    private javax.swing.JMenu edicionMenu;
    private javax.swing.JMenu herramientaMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu ventanaMenu;
    private javax.swing.JMenu vistaMenu;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        Modelo modelo = (Modelo) o;
        this.nuevaVentana(modelo);
    }
}
